apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "flower.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
{{ include "flower.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "flower.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-deployment
        {{- with .Values.deployment.image }}
        image: {{ printf "%s:%s" .name .tag }}
        imagePullPolicy: {{ .imagePullPolicy }}
        {{- end }}
        command:
        {{- range .Values.deployment.command }}
        - {{ . | quote }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        {{- if .Values.deployment.env.fromSecrets }}
        envFrom:
        {{- range $secret := .Values.deployment.env.fromSecrets }}
        - secretRef:
            name: {{ $secret }}
        {{- end }}
        {{- end }}
        env:
        {{- range $key, $val := .Values.deployment.env.config }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.global.config.name }}
              key: {{ $val }}
        {{- end }}
        {{- range $key, $val := .Values.deployment.env.secret }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.secret.name }}
              key: {{ $val }}
        {{- end }}
        {{- range $key, $val := .Values.deployment.env.values }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
