apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-collectstatic
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "back.labels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Chart.Name }}-collectstatic
        {{- with .Values.deployment.image }}
        image: {{ printf "%s:%s" .name .tag }}
        {{- end }}
        command: ["python",  "manage.py", "collectstatic", "--no-input"]
        volumeMounts:
        - name: {{ .Chart.Name }}-static
          mountPath: {{ .Values.jobCollectstatic.mountPath }}
        {{- if .Values.deployment.env.fromSecrets }}
        envFrom:
        {{- range $secret := .Values.deployment.env.fromSecrets }}
        - secretRef:
            name: {{ $secret }}
        {{- end }}
        {{- end }}
        env:
        {{- range $key, $val := .Values.deployment.env.config }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.global.config.name }}
              key: {{ $val }}
        {{- end }}
        {{- range $key, $val := .Values.deployment.env.secret }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.global.secret.name }}
              key: {{ $val }}
        {{- end }}
        {{- range $key, $val := .Values.deployment.env.values }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
      restartPolicy: {{ .Values.jobCollectstatic.restartPolicy }}

      volumes:
      - name: {{ .Chart.Name }}-static
        persistentVolumeClaim:
          claimName: static-pvc
  backoffLimit: 4
