apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $key, $val := .Values.rabbitmqSecrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
