deployment:
  replicas: 1
  image:
    name: mikolgi/foodgram-backend
    tag: v3
    imagePullPolicy: IfNotPresent
  command:
    - celery
    - -A
    - foodgram
    - worker
    - -E
    - -Q
    - holidays,weather
    - -l
    - info
  env:
    values: {}
    config: {}
    secret: {}
    fromSecrets: []
